//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Test.NongNghiep {

    [Persistent(@"data_images")]
    public partial class DataImages : XPLiteObject {
        ulong _Id;
        [Key]
        [Persistent(@"id")]
        public ulong Id {
            get { return _Id; }
            set { SetPropertyValue<ulong>(nameof(Id), ref _Id, value); }
        }
        string _Name;
        [Size(255)]
        [Persistent(@"name")]
        public string Name {
            get { return _Name; }
            set { SetPropertyValue<string>(nameof(Name), ref _Name, value); }
        }
        string _FileImage;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"file_image")]
        public string FileImage {
            get { return _FileImage; }
            set { SetPropertyValue<string>(nameof(FileImage), ref _FileImage, value); }
        }
        DateTime _TimestartCapture;
        [Persistent(@"timestart_capture")]
        public DateTime TimestartCapture {
            get { return _TimestartCapture; }
            set { SetPropertyValue<DateTime>(nameof(TimestartCapture), ref _TimestartCapture, value); }
        }
        string _StationId;
        [Size(16)]
        [Persistent(@"station_id")]
        public string StationId {
            get { return _StationId; }
            set { SetPropertyValue<string>(nameof(StationId), ref _StationId, value); }
        }
    }

}
