//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ImageHub.NongNghiep {

    [Persistent(@"data_images")]
    public partial class DataImages : XPLiteObject {
        ulong _id;
        [Key]
        [Persistent(@"id")]
        public ulong Id {
            get { return _id; }
            set { SetPropertyValue<ulong>(nameof(Id), ref _id, value); }
        }
        string _name;
        [Size(255)]
        [Persistent(@"name")]
        public string Name {
            get { return _name; }
            set { SetPropertyValue<string>(nameof(Name), ref _name, value); }
        }
        string _fileImage;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"file_image")]
        public string FileImage {
            get { return _fileImage; }
            set { SetPropertyValue<string>(nameof(FileImage), ref _fileImage, value); }
        }
        DateTime _timestartCapture;
        [Persistent(@"timestart_capture")]
        public DateTime TimestartCapture {
            get { return _timestartCapture; }
            set { SetPropertyValue<DateTime>(nameof(TimestartCapture), ref _timestartCapture, value); }
        }
        string _stationId;
        [Size(16)]
        [Persistent(@"station_id")]
        public string StationId {
            get { return _stationId; }
            set { SetPropertyValue<string>(nameof(StationId), ref _stationId, value); }
        }
    }

}
