//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace ImageHub.NongNghiep {

    [Persistent(@"logs")]
    public partial class Logs : XPLiteObject {
        ulong _id;
        [Key]
        [Persistent(@"id")]
        public ulong Id {
            get { return _id; }
            set { SetPropertyValue<ulong>(nameof(Id), ref _id, value); }
        }
        int _userId;
        [Persistent(@"user_id")]
        public int UserId {
            get { return _userId; }
            set { SetPropertyValue<int>(nameof(UserId), ref _userId, value); }
        }
        string _stationId;
        [Size(16)]
        [Persistent(@"station_id")]
        public string StationId {
            get { return _stationId; }
            set { SetPropertyValue<string>(nameof(StationId), ref _stationId, value); }
        }
        string _code;
        [Size(255)]
        [Persistent(@"code")]
        public string Code {
            get { return _code; }
            set { SetPropertyValue<string>(nameof(Code), ref _code, value); }
        }
        string _data;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"data")]
        public string Data {
            get { return _data; }
            set { SetPropertyValue<string>(nameof(Data), ref _data, value); }
        }
    }

}
